name: Update dependencies

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  update_deps:
    name: Update requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: saritasa-nest/saritasa-github-actions
