name: Update dependencies

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: saritasa-nest/saritasa-github-actions/.github/actions/updates-dependencies-python
