name: Update dependencies

on:
  pull_request:
  push:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: 3.10

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: OttoAndrey/test-actions/.github/actions/updates-dependencies-python@v1.0.1
